const React = require("react");

const {
  createGenerateClassName,
  StylesProvider,
  ThemeProvider,
  install
} = require("@material-ui/styles");

// Install the new styling solution of material-ui/styles.
// This step is temporary until the core library ships with the new solution by default.
// We have to do this before we import any material-ui components to ensure the engine is swapped and styles are applied correctly.
install();

const CssBaseline = require("@material-ui/core/CssBaseline").default;
const { SheetsRegistry } = require("jss");

const { createTheme } = require("./src/createTheme");

// We create a global map because we want wrapRootElement to render our pages using the StylesProvider.
// After the render is done we still need the generate styles from jss to be inserted in to the head.
// By making this map shared between functions we can first render and then extract the stylesheet.
const sheetsRegistryMap = new Map();

// We wrap our root elements (pages) into the material-ui StylesProvider and ThemeProvider.
// This will allow jss to generate the correct stylesheet.
const wrapRootElement = ({ element, pathname }) => {
  const generateClassName = createGenerateClassName({
    dangerouslyUseGlobalCSS: false,
    productionPrefix: "jss",
    seed: ""
  });

  // Ensure we can find the stylesheets again after the root element is wrapped and rendered with styles.
  const sheetsRegistry = new SheetsRegistry();
  sheetsRegistryMap.set(pathname, sheetsRegistry);

  const sheetsManager = new Map();

  const theme = createTheme();

  return (
    <StylesProvider
      sheetsRegistry={sheetsRegistry}
      sheetsManager={sheetsManager}
      generateClassName={generateClassName}
    >
      <ThemeProvider theme={theme}>
        <CssBaseline />
        {element}
      </ThemeProvider>
    </StylesProvider>
  );
};

// Once the root element has been properly rendered.
// We can use onRenderBody to inject the stylesheet (generated by JSS).
const onRenderBody = ({ setHeadComponents, pathname }) => {
  // Grab the sheets registry.
  const sheetsRegistry = sheetsRegistryMap.get(pathname);

  if (sheetsRegistry) {
    setHeadComponents([
      <style
        type="text/css"
        id="server-side-jss"
        key="server-side-jss"
        dangerouslySetInnerHTML={{ __html: sheetsRegistry.toString() }}
      />
    ]);

    sheetsRegistryMap.delete(pathname);
  }
};

exports.wrapRootElement = wrapRootElement;
exports.onRenderBody = onRenderBody;
